name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to ECR
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs-task-def.json
        service: your-ecs-service-name
        cluster: your-ecs-cluster-name
        wait-for-service-stability: true

    - name: Run integration tests
      run: |
        curl -f http://your-application-url/health || exit 1

    - name: Rollback on failure
      if: failure()
      run: |
        aws ecs update-service --cluster your-ecs-cluster-name --service your-ecs-service-name --force-new-deployment
