name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private
        registries: ${{ secrets.ECR_REPOSITORY_URI }}
        mask-password: true

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Push Docker image to ECR
      run: |
        docker tag myapp:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
