name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private
        mask-password: true
        registries: |
        767398088055.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Push Docker image to ECR
      run: |
        docker tag myapp:latest 767398088055.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
        docker push 767398088055.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
