name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Specify the AWS region here

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private  # Specify 'public' if using public ECR

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Tag Docker image
      run: |
        docker tag myapp:latest 767398088055.dkr.ecr.us-east-1.amazonaws.com/ci-cd-repo:latest

    - name: Push Docker image to ECR
      run: |
        docker push 767398088055.dkr.ecr.us-east-1.amazonaws.com/ci-cd-repo:latest
